// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalAPiNet6.Data;

#nullable disable

namespace MinimalAPiNet6.Migrations
{ 
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("MinimalAPiNet6.Models.ArmazemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmpresaModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraFinalDeRecebimentoDeCarga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoraInicioDeRecebimentoDeCarga")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<long>("UnidadesDeArmazenamentoMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UnidadesDeArmazenamentoOcupadas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaModelId");

                    b.ToTable("Armazem");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.CargaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmazemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CancelaEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CancelaSaida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfMotorista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeAgendamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEHoraDeChegada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEHoraDeSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeMotorista")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePorteiroEntrada")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePorteiroSaida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoDePermanenciaDentroDoArmazem")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TempoEstimadoParaDescarregar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoDeCarga")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UnidadesDeArmazenamentoDaCarga")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmazemId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Carga");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.EmpresaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.ArmazemModel", b =>
                {
                    b.HasOne("MinimalAPiNet6.Models.EmpresaModel", null)
                        .WithMany("Armazens")
                        .HasForeignKey("EmpresaModelId");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.CargaModel", b =>
                {
                    b.HasOne("MinimalAPiNet6.Models.ArmazemModel", "Armazem")
                        .WithMany("Cargas")
                        .HasForeignKey("ArmazemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinimalAPiNet6.Models.EmpresaModel", "Empresa")
                        .WithMany("Cargas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armazem");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.ArmazemModel", b =>
                {
                    b.Navigation("Cargas");
                });

            modelBuilder.Entity("MinimalAPiNet6.Models.EmpresaModel", b =>
                {
                    b.Navigation("Armazens");

                    b.Navigation("Cargas");
                });
#pragma warning restore 612, 618
        }
    }
}
